### ISSUE TITLE
Problem with # not getting passed in the query parameter

### ISSUE THREAD

**Issue by hampos** [nhomenidis/playing-the-blues-web#1]
Hey, nice work on this.
When I'm using a # in the input chord, i.e. C# the app responds with the blues chords for C.
This is probably a problem with line:31 in index.html
`request.open( "GET", "http://localhost:49804/api/blues?tonic="+chord, false );`
You should URL Encode query parameters in order to pass special characters like #.
Check this link: https://stackoverflow.com/questions/332872/encode-url-in-javascript

**Comment by nhomenidis** [comment]
Hampos,
Thanks so much for this. I was aware of the problem but wasn't sure how to fix it. Thanks again

**Comment by nhomenidis** [comment]
Issue solved.
